drone_data = [
        {
            "height": 100,
            "altitude": 200,
            "battery_health": "Good",
            "battery_percentage": 80,
            "location": "New York",
            "gps_coordinates": {"latitude": 40.7128, "longitude": -74.0060},
            "flight_routes": ["Route A", "Route B"],
            "rpm_propellers": 2000,
            "range": 500,
            "packet_loss": 0.05,
            "ping": 25,
            "wifi_connectivity": "Strong"
        },
        {
            "height": 120,
            "altitude": 300,
            "battery_health": "Excellent",
            "battery_percentage": 90,
            "location": "Los Angeles",
            "gps_coordinates": {"latitude": 34.0522, "longitude": -118.2437},
            "flight_routes": ["Route C"],
            "rpm_propellers": 2200,
            "range": 600,
            "packet_loss": 0.02,
            "ping": 20,
            "wifi_connectivity": "Strong"
        },
        {
            "height": 150,
            "altitude": 250,
            "battery_health": "Fair",
            "battery_percentage": 60,
            "location": "Chicago",
            "gps_coordinates": {"latitude": 41.8781, "longitude": -87.6298},
            "flight_routes": ["Route D", "Route E"],
            "rpm_propellers": 1800,
            "range": 450,
            "packet_loss": 0.1,
            "ping": 30,
            "wifi_connectivity": "Moderate"
        },
        {
            "height": 130,
            "altitude": 270,
            "battery_health": "Good",
            "battery_percentage": 85,
            "location": "Houston",
            "gps_coordinates": {"latitude": 29.7604, "longitude": -95.3698},
            "flight_routes": ["Route F"],
            "rpm_propellers": 2100,
            "range": 550,
            "packet_loss": 0.03,
            "ping": 28,
            "wifi_connectivity": "Strong"
        },
        {
            "height": 110,
            "altitude": 220,
            "battery_health": "Poor",
            "battery_percentage": 40,
            "location": "Phoenix",
            "gps_coordinates": {"latitude": 33.4484, "longitude": -112.0740},
            "flight_routes": ["Route G", "Route H"],
            "rpm_propellers": 1600,
            "range": 400,
            "packet_loss": 0.15,
            "ping": 35,
            "wifi_connectivity": "Weak"
        },
        {
            "height": 140,
            "altitude": 260,
            "battery_health": "Good",
            "battery_percentage": 75,
            "location": "Philadelphia",
            "gps_coordinates": {"latitude": 39.9526, "longitude": -75.1652},
            "flight_routes": ["Route I"],
            "rpm_propellers": 1950,
            "range": 525,
            "packet_loss": 0.04,
            "ping": 24,
            "wifi_connectivity": "Strong"
        },
        {
            "height": 160,
            "altitude": 280,
            "battery_health": "Excellent",
            "battery_percentage": 95,
            "location": "San Antonio",
            "gps_coordinates": {"latitude": 29.4241, "longitude": -98.4936},
            "flight_routes": ["Route J", "Route K"],
            "rpm_propellers": 2300,
            "range": 650,
            "packet_loss": 0.01,
            "ping": 18,
            "wifi_connectivity": "Strong"
        },
        {
            "height": 170,
            "altitude": 290,
            "battery_health": "Fair",
            "battery_percentage": 50,
            "location": "San Diego",
            "gps_coordinates": {"latitude": 32.7157, "longitude": -117.1611},
            "flight_routes": ["Route L"],
            "rpm_propellers": 1750,
            "range": 475,
            "packet_loss": 0.08,
            "ping": 32,
            "wifi_connectivity": "Moderate"
        },
        {
            "height": 180,
            "altitude": 300,
            "battery_health": "Good",
            "battery_percentage": 70,
            "location": "Dallas",
            "gps_coordinates": {"latitude": 32.7767, "longitude": -96.7970},
            "flight_routes": ["Route M", "Route N"],
            "rpm_propellers": 1900,
            "range": 500,
            "packet_loss": 0.06,
            "ping": 22,
            "wifi_connectivity": "Strong"
        },
        {
            "height": 190,
            "altitude": 310,
            "battery_health": "Poor",
            "battery_percentage": 30,
            "location": "San Jose",
            "gps_coordinates": {"latitude": 37.3382, "longitude": -121.8863},
            "flight_routes": ["Route O"],
            "rpm_propellers": 1550,
            "range": 350,
            "packet_loss": 0.2,
            "ping": 40,
            "wifi_connectivity": "Weak"
        }
    ]